/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marconirovereto.quartoinf.ca_provaberti2.gui;

import static com.marconirovereto.quartoinf.ca_provaberti2.Program.dbPersone;
import static com.marconirovereto.quartoinf.ca_provaberti2.Program.squadre;
import com.marconirovereto.quartoinf.ca_provaberti2.fantacalcio.Persona;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Nico
 */
public class FormSquadre extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Persona[]ArraySquadraSelez;
    String s;
    
    public FormSquadre() {
        initComponents();
        
        caricaLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleName("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Giocatore", "Ruolo", "Punteggio Giornata"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
            // TODO add your handling code here:
          int index = jList1.getSelectedIndex();
          s = (String) jList1.getSelectedValue();
          System.out.println("Value Selected: " + s.toString());
          caricaTabella(s);
              
        
    }//GEN-LAST:event_jList1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int riga = jTable1.rowAtPoint(evt.getPoint());
        int colonna = jTable1.columnAtPoint(evt.getPoint());
        String valoreDelCampo = jTable1.getModel().getValueAt(riga, colonna)+"";
        System.out.print("valore della cella: "+valoreDelCampo);
        System.out.println(" | indice della riga cliccata: "+riga);
        
        //apro la form di dettaglio sulla persona cliccata
        try {
            
        FormEdit f = new FormEdit(ArraySquadraSelez[riga], this, riga, s);
        f.setVisible(true);
        this.setEnabled(false);
        } catch (Exception e) {System.out.println("Selezionare una squadra");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public void caricaLista(){
        DefaultListModel demoList =  new DefaultListModel();
        for (String string : squadre) {
            demoList.addElement(string);
        }
        jList1.setModel(demoList);
    }
    public void caricaTabella(String s){
               //mi faccio dare il modello dei dati
        DefaultTableModel modello = (DefaultTableModel) jTable1.getModel();
        
        //ripulisco i dati presenti nel modello (serve per le volte successive alla prima)
        for (int i = modello.getRowCount() - 1; i >= 0; i--) {
            modello.removeRow(i);
        }
        ArraySquadraSelez = dbPersone.get(s).toArray(new Persona[0]);
        //carico i dati
        int nCampiDavisualizzare = 3;
        String[] dati = new String[nCampiDavisualizzare];
        int punteggioTotale=0;
        for (int i = 0; i < ArraySquadraSelez.length; i++) {
            //inserisco la singola riga di dati
            dati[0] = ArraySquadraSelez[i].nomeCognome;
            dati[1] = ArraySquadraSelez[i].ruolo;
            //sommo tutti i punteggi per metterli all'allenatore
            punteggioTotale+=ArraySquadraSelez[i].punteggio;
            if (dati[1].equals("Allenatore")) {
                dati[2] = punteggioTotale+"";
            }else{dati[2] = ArraySquadraSelez[i].punteggio+"";}
            modello.addRow(dati);
        }
        
    }
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSquadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSquadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSquadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSquadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSquadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
